/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROTO_H_RPCGEN
#define _PROTO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arithmeticParameters {
	int operands[4];
	int operandsAmount;
};
typedef struct arithmeticParameters arithmeticParameters;

#define SERVER_FUNCTIONS 0x20000001
#define FUNCTIONS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETSERVERNAME 1
extern  char ** getservername_1(void *, CLIENT *);
extern  char ** getservername_1_svc(void *, struct svc_req *);
#define GETSERVERDATE 2
extern  char ** getserverdate_1(void *, CLIENT *);
extern  char ** getserverdate_1_svc(void *, struct svc_req *);
#define INTEGERTOBINARY 3
extern  char ** integertobinary_1(int *, CLIENT *);
extern  char ** integertobinary_1_svc(int *, struct svc_req *);
#define ADDITION 4
extern  int * addition_1(arithmeticParameters *, CLIENT *);
extern  int * addition_1_svc(arithmeticParameters *, struct svc_req *);
#define MULTITPLICATION 5
extern  int * multitplication_1(arithmeticParameters *, CLIENT *);
extern  int * multitplication_1_svc(arithmeticParameters *, struct svc_req *);
extern int server_functions_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETSERVERNAME 1
extern  char ** getservername_1();
extern  char ** getservername_1_svc();
#define GETSERVERDATE 2
extern  char ** getserverdate_1();
extern  char ** getserverdate_1_svc();
#define INTEGERTOBINARY 3
extern  char ** integertobinary_1();
extern  char ** integertobinary_1_svc();
#define ADDITION 4
extern  int * addition_1();
extern  int * addition_1_svc();
#define MULTITPLICATION 5
extern  int * multitplication_1();
extern  int * multitplication_1_svc();
extern int server_functions_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arithmeticParameters (XDR *, arithmeticParameters*);

#else /* K&R C */
extern bool_t xdr_arithmeticParameters ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROTO_H_RPCGEN */
