/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proto.h"
#include <stdio.h>   /* Para printf() y perror() */
#include <stdlib.h>  /* Para malloc() y exit() */
#include <string.h>  /* Para memcpy() */
#include <time.h>    /* Para clock_gettime() y struct timespec */


static double timespec_diff_sec(const struct timespec *start, const struct timespec *end) {
	return (double)(end->tv_sec - start->tv_sec) + (double)(end->tv_nsec - start->tv_nsec) / 1e9;
}

int main (int argc, char *argv[])
{
	printf("Iniciando cliente RPC...\n");


	if (argc < 2) {
		perror("hostname required\n");
		exit (1);
	}
	char *host = argv[1];
	
	//Seteamos variables para conexión, llamado y resultado del procedimiento remoto. 
	CLIENT *clnt;
	respuesta  *result_sumar_arreglos_1;
	entrada *sumar_arreglos_1_arg = malloc(sizeof(entrada)); //Asignamos memoria para el argumento de entrada

	printf("Preparando conexión con el servidor RPC en %s...\n", host);

	//Iniciamos conexión con el servidor RPC. Si falla, se muestra un error y se termina el programa.
	clnt = clnt_create (host, SUMADOR_PROG, SUMADOR_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	printf("Conexión establecida con el servidor RPC en %s\n", host);

	//Definimos los argumentos de entrada
	int arreglo1[200] = {0}; //Inicializamos el arreglo con ceros
	int arreglo2[200] = {0}; //Inicializamos el arreglo con ceros
	for (int i = 0; i < 200; i++) {
		arreglo1[i] = i + 1; //Llenamos el arreglo con números del 1 al 200
		arreglo2[i] = (i + 1) * 2; //Llenamos el arreglo con números del 2 al 400
	}
	memcpy(sumar_arreglos_1_arg->arreglo_A, arreglo1, sizeof(arreglo1));
	memcpy(sumar_arreglos_1_arg->arreglo_B, arreglo2, sizeof(arreglo2));

	printf("Argumentos de entrada preparados. Llamando al procedimiento remoto 'sumar_arreglos_1'...\n");

	//Medimos tiempo antes de llamar al procedimiento remoto.
	struct timespec t_start, t_ready;
	if (clock_gettime(CLOCK_MONOTONIC, &t_start) == -1) {
		perror("clock_gettime");
		return 1;
	}

	//Llamamos al procedimiento remoto 'sumar_arreglos_1' declarado en el archivo proto.h y almacenamos el resultado. Si falla, se muestra un error.
	result_sumar_arreglos_1 = sumar_arreglos_1((void*)sumar_arreglos_1_arg, clnt);
	if (result_sumar_arreglos_1 == (respuesta *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Respuesta recibida del procedimiento remoto 'sumar_arreglos_1'. Procesando resultado...\n");

	// Medimos el tiempo después de recibir la respuesta del procedimiento remoto.
	if (clock_gettime(CLOCK_MONOTONIC, &t_ready) == -1) {
		perror("clock_gettime");
		return 1;
	}

	// Podemos procesar el arreglo pero no es necesario para medir el tiempo de respuesta del procedimiento remoto, así que lo omitimos.
	double elapsed = timespec_diff_sec(&t_start, &t_ready);
	printf("Tiempo hasta que el hijo terminó: %.6f segundos\n", elapsed);

	//Muestra el array resultado de la suma de los dos arreglos enviados como argumento.
	printf("Resultado de la suma de los arreglos:\n");
	for (int i = 0; i < 200; i++) {
		printf("%d ", result_sumar_arreglos_1->resultado[i]);
	}
	printf("\n");

	clnt_destroy (clnt);

	free(sumar_arreglos_1_arg); //Liberamos la memoria asignada para el argumento de entrada

	return 0;
}
