all: ejecutable_master ejecutable_slave

ejecutable_slave: slave/main_slave.c
	gcc slave/main_slave.c -o slave/ejecutable_slave

ejecutable_master: master/master.c
	gcc master/master.c -o master/ejecutable_master