all: ejecutable_master.out ejecutable_slave.out

ejecutable_slave.out: slave/main_slave.c
	gcc slave/main_slave.c -o slave/ejecutable_slave.out

ejecutable_master.out: master/master.c
	gcc master/master.c -o master/ejecutable_master.out