all: ejecutable_cliente.out ejecutable_servidor.out ejecutable_programaMain.out

ejecutable_programaMain.out: programaMain.c
	gcc programaMain.c -o ejecutable_programaMain.out

ejecutable_cliente.out: cliente.c
	gcc cliente.c -o ejecutable_cliente.out

ejecutable_servidor.out: servidor.c
	gcc servidor.c -o ejecutable_servidor.out