all: hijo_exec.out padre_execv.out padre_system.out

hijo_exec.out: hijo_exec.c
	gcc hijo_exec.c -o hijo_exec.out

padre_execv.out: padre_execv.c
	gcc padre_execv.c -o padre_execv.out	

padre_system.out: padre_system.c
	gcc padre_system.c -o padre_system.out