/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proto.h"
#include <time.h>
static int64_t timespec_diff_nanosec(const struct timespec *start, const struct timespec *end) {
	return (int64_t)(end->tv_sec - start->tv_sec) * 1000000000LL + (int64_t)(end->tv_nsec - start->tv_nsec);
}


int
main (int argc, char *argv[])
{
	if (argc < 2) {
		printf ("Error, indicar IP del host.\n");
		exit (1);
	}
	
	char *host = argv[1];
	
	//Seteamos variables para conexión, llamado y resultado del procedimiento remoto. 
	CLIENT *clnt;
	int  *result_1;
	char *crear_hijo1b_1_arg; //Dummy porque el procedimiento no recibe argumetnos.

	//Iniciamos conexión con el servidor RPC. Si falla, se muestra un error y se termina el programa.
	clnt = clnt_create (host, EJERCICIO1, EJERCICIO1VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	//Medimos tiempo antes de llamar al procedimiento remoto.
	struct timespec t_start, t_ready;
	if (clock_gettime(CLOCK_MONOTONIC, &t_start) == -1) {
		perror("clock_gettime");
		return 1;
	}

	//Llamamos al procedimiento remoto 'crear_hijo1b_1' declarado en el archivo proto.h y almacenamos el resultado. Si falla, se muestra un error.
	result_1 = crear_hijo1b_1((void*)&crear_hijo1b_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	//Procesamos el resultado de la llamada
	if(*result_1 == 0){
		//Si el resultado es 0, el hijo se creó correctamente. Medimos el tiempo hasta que el hijo terminó.
		if (clock_gettime(CLOCK_MONOTONIC, &t_ready) == -1) {
            perror("clock_gettime");
			return 1;
		}	

		int64_t elapsed = timespec_diff_nanosec(&t_start, &t_ready);
        printf("Tiempo hasta que el hijo terminó: %ld microsegundos\n", elapsed / 1000);
	}else{
		//Si el resultado no es 0, hubo un error al crear el hijo. Mostramos un mensaje de error.
		fprintf(stderr, "Error al crear el hijo: código %d\n", *result_1);
		return 1;
	}

	clnt_destroy (clnt);
}
