/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROTO_H_RPCGEN
#define _PROTO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define EJERCICIO1 0x20000001
#define EJERCICIO1VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CREAR_HIJO1B 1
extern  int * crear_hijo1b_1(void *, CLIENT *);
extern  int * crear_hijo1b_1_svc(void *, struct svc_req *);
#define FUNCIONPRUEBA 2
extern  int * funcionprueba_1(void *, CLIENT *);
extern  int * funcionprueba_1_svc(void *, struct svc_req *);
extern int ejercicio1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CREAR_HIJO1B 1
extern  int * crear_hijo1b_1();
extern  int * crear_hijo1b_1_svc();
#define FUNCIONPRUEBA 2
extern  int * funcionprueba_1();
extern  int * funcionprueba_1_svc();
extern int ejercicio1_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROTO_H_RPCGEN */
