/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <unistd.h>
#include <sys/wait.h>
#include "proto.h"

int *
crear_hijo1b_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result = 0;

	int status = system("./hijo_exec.out");
	if (status == -1) {
		perror("system falló");
		result = 1;
	}

	return &result;
}

int *
funcionprueba_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
