/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <unistd.h>
#include <sys/wait.h>
#include "proto.h"

int *
crear_hijo1b_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result = 0;

	pid_t pid = fork();
	if (pid < 0) {
		perror("fork");
		result = 1;
	} else if (pid == 0) {
		// child
		
        char exec_path[] = "./hijo_exec.out";
		execv(exec_path, NULL);
        //falla el execv
        perror("execv falló");
		result = 1;	
	} else {
		// parent
		
		if (wait(NULL) == -1) {
			perror("wait falló");
			result = 1;
		}
	}

	return &result;
}

int *
funcionprueba_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
