/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proto.h"
#include <stdio.h>

respuesta *
sumar_arreglos_1_svc(entrada *argp, struct svc_req *rqstp)
{
	respuesta *result = malloc(sizeof(respuesta));
	printf("Servidor: Recibi los arreglos\n");
	for(int i = 0; i < 200; i++)
	{
		result->resultado[i] = argp->arreglo_A[i] + argp->arreglo_B[i];
	}
	printf("Servidor: Sume los arreglos\n");
	free(result);
	return result;
}
