/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROTO_H_RPCGEN
#define _PROTO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct entrada {
	int arreglo_A[200];
	int arreglo_B[200];
	char padding[2496];
};
typedef struct entrada entrada;

struct respuesta {
	int resultado[200];
	char padding[1248];
};
typedef struct respuesta respuesta;

#define SUMADOR_PROG 0x20000001
#define SUMADOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR_ARREGLOS 1
extern  respuesta * sumar_arreglos_1(entrada *, CLIENT *);
extern  respuesta * sumar_arreglos_1_svc(entrada *, struct svc_req *);
extern int sumador_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR_ARREGLOS 1
extern  respuesta * sumar_arreglos_1();
extern  respuesta * sumar_arreglos_1_svc();
extern int sumador_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entrada (XDR *, entrada*);
extern  bool_t xdr_respuesta (XDR *, respuesta*);

#else /* K&R C */
extern bool_t xdr_entrada ();
extern bool_t xdr_respuesta ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROTO_H_RPCGEN */
