/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proto.h"

respuesta *
sumar_arreglos_1_svc(entrada *argp, struct svc_req *rqstp)
{
	respuesta *result;

	for(int i = 0; i < 200; i++)
	{
		result->resultado[i] = argp->arreglo_A[i] + argp->arreglo_B[i];
	}

	return result;
}
