all: client/ejecutable_cliente.out server/ejecutable_servidor.out

client/ejecutable_cliente.out: client/main_client.c
	gcc client/main_client.c -o client/ejecutable_cliente.out

server/ejecutable_servidor.out: server/main_server.c
	gcc server/main_server.c -o server/ejecutable_servidor.out