all: client/ejecutable_cliente server/ejecutable_servidor

client/ejecutable_cliente: client/main_client.c
	gcc client/main_client.c -o client/ejecutable_cliente

server/ejecutable_servidor: server/main_server.c
	gcc server/main_server.c -o server/ejecutable_servidor